config/routes.rb
Rails.application.routes.draw do
  resources :listings
  get 'home/index'
  get 'seller' => 'listings#seller'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "listings#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord

validates :course, :book, :price, presence: true
validates :price, numericality: { greater_than: 0 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  has_many :listings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
 devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new,:create,:edit,:update,:destroy,:seller]
  before_action :check_user, only: [:edit, :update, :destroy]
  def seller
    @listings = Listing.where(user: current_user).order("updated_at DESC")
  end
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.order("updated_at DESC")

  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:course, :book, :price)
    end

    def check_user
      if current_user!=@listing.user
        redirect_to root_url, alert: "Posted by someone else"
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/home/index.html.erb
<ul>
  <% if user_signed_in? %>
  <li>
      <%= link_to "Sign Out", destroy_user_session_path, method: delete %>
  </li>
  <% else %>
    <li>
        <%= link_to "Sign In", new_user_session_path %>
    </li>
    <li>
      <%= link_to "Sign Up", new_user_registration_path %>
    </li>
    <% end %>
</ul>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_footer.html.erb
<p>Copyright 2018</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/#">Bruin4.0</a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li><%= link_to "Manage", seller_path %></li>
      <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>

  </div>


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bruin4.0</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

  <%= render 'layouts/header' %>
  <div class = "container">
    <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
    <% end %>
    <% end %>
    <%= yield %>

  </div>
</body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
  <div id="error_explanation" class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :course %>
    <%= form.text_field :course, id: :listing_course, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :textbook %>
    <%= form.text_field :book, id: :listing_book, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :listing_price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Update Post</h1>

<%= render 'form', listing: @listing %>
<table>
  <tbody>
    <tr>
<td><%= button_to 'Show', @listing, :method => "get", class: "btn btn-primary btn-xs" %></td>
<td><%= button_to 'Back', listings_path, :method => "get", class: "btn btn-primary btn-xs" %></td>
</tr>
</tbody>
</table>

app/views/listings/index.html.erb
<h1>Posts</h1>

<table class = "table">
  <thead>
    <tr>
      <th class = "center">Course</th>
      <th class = "center">TextBook</th>
      <th class = "center">Price</th>
      <th class = "center">Sold by </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td class = "center"><%= listing.course %></td>
        <td class = "center"><%= listing.book %></td>
        <td class = "center"><%= number_to_currency(listing.price) %></td>
        <td class = "center"><%= "#{listing.user.name}"%></td>
        <td><%= button_to 'View', listing, :method => "get", class: "btn btn-primary btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= button_to 'New Post', new_listing_path,:method => "get", class: "btn btn-primary" %>

app/views/listings/new.html.erb
<h1>New Post</h1>

<%= render 'form', listing: @listing %>

<%= button_to 'Back', listings_path, :method => "get", class: "btn btn-primary btn-xs" %>

app/views/listings/seller.html.erb
<h1>Your Posts</h1>

<table class ="table">
  <thead>
    <tr>
      <th class = "center">Course</th>
      <th class = "center">TextBook</th>
      <th class = "center">Price</th>
      <th class = "center">Sold by </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td class = "center"><%= listing.course %></td>
        <td class = "center"><%= listing.book %></td>
        <td class = "center"><%= number_to_currency(listing.price) %></td>
        <td class = "center"><%= "#{listing.user.name}"%></td>
        <td><%= button_to 'View', listing, :method => "get", class: "btn btn-primary btn-xs"%></td>
        <% if (user_signed_in?) && (current_user == listing.user) %>
          <td><%= button_to 'Edit', edit_listing_path(listing), method: :get, class: "btn btn-primary btn-xs" %></td>
          <td><%= button_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-primary btn-xs" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Post', new_listing_path, :method => "get", class: "btn btn-primary" %>

app/views/listings/show.html.erb
<p>
  <strong>Course:</strong>
  <%= @listing.course %>
</p>

<p>
  <strong>TextBook:</strong>
  <%= @listing.book %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@listing.price) %>
</p>

<p>
  Sold by <%= mail_to @listing.user.email, "#{@listing.user.name}" %>
</p>

<table>
  <tbody>
    <tr>
<% if current_user == @listing.user %>
<td><%= button_to 'Edit', edit_listing_path(@listing), :method => "get", class: "btn btn-primary btn-xs" %></td>
<% end %>
<td><%= button_to 'Back', listings_path, :method => "get", class: "btn btn-primary btn-xs" %></td>
</tr>
</tbody>
</table>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>